Cloud bastion
Otus-DevOps-2020-05/saniller_infra pull request #4
Opened 2020-06-23 11:58 UTC by saniller

# Выполнено ДЗ №5

 - [ ] Основное ДЗ

## В процессе сделано:
 - Подключение по ssh к хосту, не имеющему внешний IP через ssh к bastion-host. Использовался forwarding ключей доступа.
 - Подключение по ssh к хосту, не имеющему внешний IP через VPN-сервер, установленный на bastion-host.

## PR checklist
 - [ ] Выставил label с темой домашнего задания

2020-06-24 05:50 UTC, mrgreyves requested changes
Здравствуйте! Проверил ваше дз. Оставил комментарий к файлу. Возвращаю на доработку.

2020-06-24 05:50 UTC, mrgreyves commented on setupvpn.sh
> +#!/bin/bash
В этом файле проблемы с переносами строк

2020-06-25 10:17 UTC, saniller commented
не знаю - почему не проходят тесты

2020-06-25 13:53 UTC, mrgreyves requested changes
Здравствуйте! Вам нужно посмотреть результаты теста. Они доступны в разделе с тестами.
ЗЫ: Не удается подключиться к хосту в приватной сети. Из-за этого тесты и сваливаются.
ЗЫы: если возникнут вопросы, предлагаю обсудить их в слаке =)

2020-07-02 09:31 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-07-11 17:52 UTC, merged